### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.deformation_graph_old'

### ISSUE THREAD

**Issue by YH188** [rqhuang88/DFR#1]
Hello, thank you for your assistance. 
How can I resolve this error? ModuleNotFoundError: No module named 'lib.deformation_graph_old'.
In running train.py under the DFM folder, the error occurs that it cannot find data/scape/cache_scape_open_wks_train.pt. How can I solve this problem?
Thank you very much.

**Comment by puhuajiang** [comment]
Sorry for the problem, I will refine the code today.

**Comment by puhuajiang** [comment]
I just added "lib" to the repo, for any other questions please feel free to ask here.

**Comment by YH188** [comment]
> I just added "lib" to the repo, for any other questions please feel free to ask here.

In running train.py under the DFM folder, the error occurs that it cannot find data/scape/cache_scape_open_wks_train.pt. How can I solve this problem?
Thank you very much.

**Comment by puhuajiang** [comment]
That part will also be fixed soon by the other contributor.

**Comment by puhuajiang** [comment]
Just fixed
