### ISSUE TITLE
Error Not enough values to unpack 

### ISSUE THREAD

**Issue by Heni-Loukil** [rqhuang88/DFR#2]
Hello when I try the training code I get an error "  --> loading dataset from cache
Traceback (most recent call last):
  File "C:\Users\henil\PycharmProjects\pythonProject\DFM\train.py", line 166, in <module>
    train_net(cfg)
  File "C:\Users\henil\PycharmProjects\pythonProject\DFM\train.py", line 71, in train_net
    train_dataset = M2PDataset(dataset_path_train, name=cfg["dataset"]["name"],
  File "C:\Users\henil\PycharmProjects\pythonProject\DFM\dataset.py", line 30, in __init__
    (
ValueError: not enough values to unpack (expected 7, got 6)" I tried fixing the error by simply eliminating the self.phi_inv_list from the loaded values to make it 6 for both but then the loss doesn't converge , I tried also putting it back to both lists but still got the loss isn't converging, Thank you in advance for fixing this bug

**Comment by puhuajiang** [comment]
It seems like that your dataset dose not have "corres" dir?  The "corres" dir contains the vts file(can be used as GT correspondences for remesh scape and faust dataset).  You can either download the corres dir as shown in readme  or just delete all the "self.vts_list" in dataset.py.

**Comment by Heni-Loukil** [comment]
Okay I will try it thanks. 
After training the modified DGCNN and the DFM with train.py, the loss normally get to what value exactly ?

**Comment by puhuajiang** [comment]
I will less than 10.

**Comment by Heni-Loukil** [comment]
I checked the data folder and it turned out that I have the corres dir with the vts files but still with that I just get a loss of 51% after 20 epochs .
